version: "3"

services:
  bot:
    env_file:
      - .bot.env
    build:
      context: "."
      dockerfile: Dockerfile
    # environment:
      # - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    #volumes:
      # - "/codebase:/codebase"
      # - "/storage:/storage"
    restart: unless-stopped